IDCP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from department import views as dv
from student import views as sv

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',dv.welcome,name='welcome'),
    url(r'^department/$',dv.index,name='index'),
    url(r'^student/$',sv.index,name='s_index'),
    #url(r'^special/',views.special,name='special'),
    url(r'^department/',include('department.urls')),
    url(r'^student/',include('student.urls')),
    url(r'^logout/$', dv.user_logout, name='logout'),
    url(r'^logout/$', sv.user_logout, name='s_logout'),
    url('project/', dv.project, name="project"),
    url('team/', dv.team, name="team"),
]

department/urls.py
from django.urls import re_path as url
from department import views
# SET THE NAMESPACE!
app_name = 'department'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url('register/',views.register,name='register'),
    url('user_login/',views.user_login,name='user_login'),
    url('course_add/', views.courseAdd, name='course_add'),
    url('notsadd/', views.Notification),
    url(r'^approve/(?P<student_id>\d+)$', views.approve_student, name='approve'),
    url('approve_all', views.approve_all, name='approve_all'),
    url(r'^reject/(?P<student_id>\d+)$', views.reject_student, name='reject'),
    url(r'^delete/(?P<course_id>\d+)$', views.courseDel, name='delete'),
    url(r'^not_delete/(?P<not_id>\d+)$', views.notDel, name='not_delete'),
    url(r'^unenroll/(?P<enroll_id>\d+)$', views.unEnroll, name='unenroll'),
    url(r'^download/(?P<course_id>\d+)$', views.downloadSyl, name='download'),
    url('assign_fac', views.assign_fac, name='assign_fac'),
    url('print_preview', views.enrollInfo, name='print_preview'),
    url('student_preview', views.StudentRegInfo, name='student_preview'),

    


]

student/urls.py
from django.urls import re_path as url
from student import views
# SET THE NAMESPACE!
app_name = 'student'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[
    url('register/',views.register,name='register'),
    url('student_login/',views.student_login,name='student_login'),
    url('stu/', views.index, name='stu'),
    url(r'^enroll/(?P<course_id>\d+)$', views.enrollStudent, name='enroll_student'),
    url(r'^request_removal/(?P<enrol_id>\d+)$', views.requestRemoval, name='request_removal'),
]

student/models.py
from django.db import models
from django.contrib.auth.models import User
from department.models import CourseInfo, DepProfileInfo
class StudentInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    exam_reg_no =models.CharField(max_length=12)
    phone = models.CharField(max_length=12, unique=True)
    department = models.ForeignKey(DepProfileInfo, on_delete=models.CASCADE)
    course = models.CharField(max_length=30)
    approved = models.BooleanField(default=False)

    def __str__(self):
      return self.exam_reg_no

class Enroll(models.Model):
  student= models.OneToOneField(StudentInfo,on_delete=models.CASCADE)
  course = models.ForeignKey(CourseInfo, on_delete=models.CASCADE)
  request_removal = models.BooleanField(default=False)

  def __str__(self):
      return self.student

class Attendance(models.Model):
  date = models.DateField()
  student = models.ForeignKey(StudentInfo, on_delete=models.CASCADE)

  def __str__(self):
    return str(self.date)

student/forms.py
from dataclasses import field
from django import forms
from student.models import StudentInfo, Enroll
from django.contrib.auth.models import User
class StudentForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','first_name','last_name','email','password',)
class StudentProfileInfoForm(forms.ModelForm):
     class Meta():
         model = StudentInfo
         fields = ('exam_reg_no','phone','department','course')

student/views.py
from django.shortcuts import render
from student.forms import StudentForm, StudentProfileInfoForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from department.models import DepProfileInfo, CourseInfo, Notification
from student.models import Enroll, StudentInfo
from django.contrib import messages
from django.contrib.auth.models import User

def index(request):
    student = StudentInfo.objects.get(user=request.user)
    studey_dep = DepProfileInfo.objects.get(id=student.department.id)
    deps=DepProfileInfo.objects.all()
    try:
        en = Enroll.objects.get(student=student)
    except Enroll.DoesNotExist:
        en = 0
    cor=[]
    corse = CourseInfo.objects.filter()
    for c in corse:
        print(studey_dep.id, c.department.id)
        if c.department.id != studey_dep.id:
            cor.append(c)
    r=[]
    for d in deps:
        c = CourseInfo.objects.filter(department=d.id)
        r.append({'dep':d, 'cor':c})

    if(en != 0):
        notsin = Notification.objects.filter(department= en.course.department)
    else:
        notsin = {}


    return render(request,'student/index.html', context={'r':r, 'student': student, 'cor':cor, 'en':en, 'notsin':notsin})

def enrollStudent(request, course_id):
    stu = StudentInfo.objects.get(user=request.user)
    cor = CourseInfo.objects.get(id=course_id)
    en = Enroll(student = stu, course = cor)
    en.save()
    cor.seats_left-=1
    cor.save()
    return HttpResponseRedirect(reverse('s_index'))

def requestRemoval(request, enrol_id):
    if enrol_id:
        en = Enroll.objects.get(id=enrol_id)
        en.request_removal = True
        en.save()
    return HttpResponseRedirect(reverse('s_index'))

@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('welcome'))

def register(request):
    registered = False
    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')
        email = request.POST.get('email')
        if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
            st = User(username=username, first_name=first_name, last_name=last_name, email=email, is_staff=0)
            st.set_password(password)
            st.save()

            phone = request.POST.get('phone')
            dep_id = request.POST.get('department')
            department = DepProfileInfo.objects.get(id=dep_id)
            course = request.POST.get('course')
            st_inf = StudentInfo(phone=phone, department=department, course=course, user_id=st.id, approved=0)
            st_inf.save()
            messages.success(request, "Regitration Success!")
            return HttpResponseRedirect(reverse('welcome'))
        else:
            messages.warning(request, "Username or email already exist!")
            return HttpResponseRedirect(reverse('welcome'))


def student_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and not user.is_staff:
                login(request,user)
                return HttpResponseRedirect(reverse('s_index'))
            else:
                messages.warning(request, "You are not a student!")
                return HttpResponseRedirect(reverse('welcome'))
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.warning(request, "Invalid login details given")
            return HttpResponseRedirect(reverse('welcome'))
    else:
        return render(request, 'student/login.html', {})

templates/student/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>IDCP</title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
</head>
  <body>
    
    <div>
    {% block body_block %}
    {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

templates/student/index.html
{% extends "department/base.html" %}

{% block body_block %}

{% if user.is_authenticated %}
<div class="container bg-light p-3 rounded">
  <div class="row">
    <div class="col-md-3 mb-3">

      <div class="list-group" id="list-tab" role="tablist">
        <a class="list-group-item list-group-item-action list-group-item-dark active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home"><i class="bi bi-house-fill"></i>&nbsp; Home</a>
        <!-- <a class="list-group-item list-group-item-action list-group-item-dark" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile"><i class="bi bi-pen-fill"></i>&nbsp; Edit Profile</a> -->
        <!-- <a class="list-group-item list-group-item-action list-group-item-dark" id="list-student-list" data-toggle="list" href="#list-student" role="tab" aria-controls="student"><i class="bi bi-people-fill"></i>&nbsp; Students</a> -->
        <a class="list-group-item list-group-item-action list-group-item-dark" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages"><i class="bi bi-layers-fill"></i>&nbsp; Courses</a>
        <!-- <a class="list-group-item list-group-item-action list-group-item-dark" id="list-application-list" data-toggle="list" href="#list-application" role="tab" aria-controls="applications"><i class="bi bi-file-earmark-person-fill"></i>&nbsp; Applications</a> -->
        <a class="list-group-item list-group-item-action list-group-item-dark" id="list-notification-list" data-toggle="list" href="#list-notification" role="tab" aria-controls="notification"><i class="bi bi-bell-fill"></i>&nbsp; Notifications</a>
        <a class="list-group-item list-group-item-action list-group-item-dark"  data-toggle="modal" data-target="#logoutModalCenter" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings"><i class="bi bi-x-square-fill"></i>&nbsp; Logout</a>

      </div>
    </div>
    <div class="col">
      <div class="tab-content" id="nav-tabContent">
        <div class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
            <div class="">
              <div class="card">
                <div class="card-body">
                  <h5 class="card-title">{{ student.user.first_name}} {{ student.user.last_name}} ({{student.user}})</h5>
                  <p class="card-subtitle mb-2 text-muted"> &emsp13;
                    {% if student.approved %}
                    <span class="badge badge-pill badge-primary"><i class="bi bi-patch-check-fill"></i> verified</span>
                    {% else %}
                    <span class="badge badge-pill badge-warning">Profile not approved by your department</span>
                  {% endif %}
                  </p>
                  <p class="card-text">{{student.course}} @ {{student.department}}, CUSAT</p>
                  <a href="mailto:{{student.user.email}}" class="text-dark">{{student.user.email}}</a> | <a href="tel:+{{student.phone}}" class="text-dark">{{student.phone}}</a>
                </div>
              </div>

              <div class="card mt-3">
                <div class="alert alert-dark m-2" role="alert">
                  <b>Enrolled Course</b>
                </div>
                {% if en == 0 %}
                <div class="m-2">
                  You have not enrolled into any courses.
                </div>
                {% else %}
                <div class="m-4 row">
                  <div class="col-md-10"><b>{{en.course.course_code}} - {{en.course.course_name}}</b><br>
                    {{en.course.department}}</div>
                  <div class="col-md-2 my-auto">
                    <a class="btn btn-sm btn-outline-secondary" href="{% url 'department:download' en.course.id %}"><i class="bi bi-cloud-arrow-down-fill"></i> Syllabus</a>
                  </div>


                </div>
                {% endif %}
              </div>
            </div>


        </div>
        <div class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">...</div>
        <div class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">
          <div class="alert alert-dark" role="alert">
            <b>Courses Available</b>
          </div>
          <div class="bg-white  overflow-auto" style="height: 500px;">

              {% for c in cor %}
              <div class="list-group-item list-group-item-action">
                <div class="row">

                  <div class="col-md-6">
                      <b>{{c.course_code}} - {{c.course_name}}</b><br>
                      <small>
                      <i>{{c.department}}</i><br>
                      Start date: <b>{{c.start_date}}</b> &nbsp; | &nbsp;
                      No of seats left: </small><b><span class="badge badge-pill badge-info">{{c.seats_left}}/{{c.no_of_seats}}</span></b>

                  </div>
                  <div class="col-md-2 my-auto">
                    <a href="" class="btn btn-sm btn-outline-dark" data-toggle="modal" data-target="#ht{{ forloop.counter }}">More info</a>
                </div>
                <div class="col-md-4 my-auto mx-auto">
                 {% if student.approved and en == 0 and c.seats_left > 0  %}

                  <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="modal" data-target="#enrolled{{ forloop.counter }}"><i class="bi bi-person-plus-fill"></i> Enroll</button>
                  {% else %}
                  {% endif %}
                  {% if c.seats_left == 0 %}
                  <span class="badge badge-pill badge-danger">Housefull!</span>
                  {% endif %}
                  {% if en != 0 and en.course == c %}
                  <span class="badge badge-pill badge-warning">Enrolled</span>
                  {% if en.request_removal == False %}
                  <button type="button" class="btn btn-sm btn-outline-danger" data-toggle="modal" data-target="#unenrolled{{ forloop.counter }}"><i class="bi bi-person-plus-fill"></i>Request Unenroll</button>
                  {% else %}
                  <span class="badge badge-pill badge-danger">Unenroll request sent!</span>
                  {% endif %}
                  {% endif %}



                </div>


            </div>
          </div>

           <!-- Course Modal -->
           <div class="modal fade" id="ht{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLongTitle" aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="exampleModalLongTitle">{{c.course_code}} - {{c.course_name}}</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  Start Date : {{c.start_date}} <br>
                  Slot : {{c.slot}} &nbsp;&nbsp;&nbsp; Hours per week : {{c.hours_per_week}} <br>
                  No of seats : {{c.no_of_seats}} <br>

                  <a href="{% url 'department:download' c.id %}">Syllabus</a>

                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-dark" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
            </div>

            <!-- modal -->
                <div class="modal fade" id="enrolled{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="logoutModalCenterTitle" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered" role="document">
                    <div class="modal-content">
                      <div class="modal-header">
                        <h5 class="modal-title" id="logoutModalLongTitle">Confirm Enrollment</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                          <span aria-hidden="true">&times;</span>
                        </button>
                      </div>
                      <div class="modal-body">

                        You will have to contact your department to cancel enrollment. <br>
                        Confirm enrollment to course {{c.name}}?
                      </div>
                      <div class="modal-footer">
                        {% if user.is_authenticated %}
                        <button type="button" class="btn btn-light" data-dismiss="modal">Go back</button>
                        <a type="button" class="btn btn-sm btn-danger" href="{% url 'student:enroll_student' c.id %}">Confirm</a>
                        {% endif %}
                      </div>
                    </div>
                  </div>
                </div>


                            <!-- modal -->
                    <div class="modal fade" id="unenrolled{{ forloop.counter }}" tabindex="-1" role="dialog" aria-labelledby="logoutModalCenterTitle" aria-hidden="true">
                      <div class="modal-dialog modal-dialog-centered" role="document">
                        <div class="modal-content">
                          <div class="modal-header">
                            <h5 class="modal-title" id="logoutModalLongTitle">Confirm Unenrollment</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                              <span aria-hidden="true">&times;</span>
                            </button>
                          </div>
                          <div class="modal-body">

                            Do you want to request the department to unenrol you from the course? This is needed to be confirmed from their part also.<br>
                            Confirm unenrollment to course {{c.name}}?
                          </div>
                          <div class="modal-footer">
                            {% if user.is_authenticated %}
                            <button type="button" class="btn btn-light" data-dismiss="modal">Go back</button>
                            {% if en != 0 %}<a type="button" class="btn btn-sm btn-danger" href="{% url 'student:request_removal' en.id %}">Confirm</a>{% endif %}
                            {% endif %}
                          </div>
                        </div>
                      </div>
                    </div>

                  {% empty %}
                  <p class="pl-5">No courses available.. </p>
                  {% endfor %}


            </div>

        </div>
        <div class="tab-pane fade" id="list-student" role="tabpanel" aria-labelledby="list-student-list">

          {% for s in stude %}
          <div class="list-group-item list-group-item-action">
            <div class="row">
            <div class="col-sm-10">{{ s.exam_reg_no }}
            </div>
            <div class="col-sm-2">
              <small>{{ n4.publish_date }}</small></div>
          </div>
          </div>
          {% endfor %}
        </div>
        <div class="tab-pane fade" id="list-application" role="tabpanel" aria-labelledby="list-application-list">approve application</div>
        <div class="tab-pane fade" id="list-notification" role="tabpanel" aria-labelledby="list-notification-list">

          {% if en != 0 %}

          {% for n4 in notsin %}
          <div class="list-group-item list-group-item-action">
            <div class="row">
            <div class="col-sm-10">{{ n4.notification }}
            </div>
            <div class="col-sm-2">
              <small>{{ n4.publish_date }}</small></div>
          </div>
          </div>
          {% empty %}

          <div class="list-group-item list-group-item-action">
            <div class="row">
              No notification from your course enrolled department.
          </div></div>
          {% endfor %}

          {% else %}
          <div class="list-group-item list-group-item-action">
            <div class="row">
              You are not enrolled to any course.
          </div></div>
          {% endif %}
        </div>
        <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">...</div>
      </div>
    </div>
  </div>
</div>

<!-- modal -->
<div class="modal fade" id="logoutModalCenter" tabindex="-1" role="dialog" aria-labelledby="logoutModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="logoutModalLongTitle">Confirm Logout</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        Do you want to logout?
      </div>
      <div class="modal-footer">
        {% if user.is_authenticated %}
        <button type="button" class="btn btn-light" data-dismiss="modal">Go back</button>
        <a class="btn btn-dark" href="{% url 'logout' %}"> Confirm</a>
        {% endif %}
      </div>
    </div>
  </div>
</div>


{% else %}

<div class="container">
  <div class="alert alert-warning" role="alert">
    Session Expired! <a href="{% url 'welcome' %}">Login again</a>
  </div>
</div>
{% endif %}
<br>
{% endblock %}

templates/student/login.html
{% block login %}
  <div class="container">
    <br>
    <div class="card col-md-4 text-center" style="margin: 0 auto; float: none; margin-bottom: 10px;"><br>
      <h3>Login</h3>
      <br>
  <form method="post" action="{% url 'student:student_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><br>
<label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><br><br>
<input type="submit" name="" value="Login">&nbsp;
New user?&nbsp;&nbsp;<a href="{% url 'student:register' %}">Register</a><br><br>
</form>
  </div>
</div>
{% endblock %}

templates/student/registration.html
{% extends "student/base.html" %}
{% load static %}
{% block body_block %}

<nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'welcome' %}">IDCP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon navbar-light"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li><a class="navbar-link  text-dark" href="#">Student Login</a></li>&nbsp;&nbsp; 
        {# Some logic on what to display for last item#}
        <!-- {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a class="navbar-link  text-dark" href="{% url 'department:user_login' %}">Department Login</a></li>
        {% endif %} -->
    </ul>
  </div>
</nav>
<div class="container">
<div class="jumbotron" style="background-image: url('../../static/campus.png');background-repeat: no-repeat;background-size: cover;">
  <h2><B>Interdisciplinary Course Portal</B></h2>
  <h4>Cochin University of Science and Technology</h4>
  {% if user.is_authenticated %}
      <h5>Hello {{ user.username }}</h5>
  

  {% endif %}
</div>

  <div class="container">
    <div class="card" style="margin: 0 auto; float: none; margin-bottom: 10px;">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{s_user_form.as_p}}
          {{ s_profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}