IDCP/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.urls import re_path as url
from department import views as dv
from student import views as sv

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$',dv.welcome,name='welcome'),
    url(r'^department/$',dv.index,name='index'),
    url(r'^student/$',sv.index,name='s_index'),
    #url(r'^special/',views.special,name='special'),
    url(r'^department/',include('department.urls')),
    url(r'^student/',include('student.urls')),
    url(r'^logout/$', dv.user_logout, name='logout'),
    url(r'^logout/$', sv.user_logout, name='s_logout'),
    url('project/', dv.project, name="project"),
    url('team/', dv.team, name="team"),
]

department/urls.py
from django.urls import re_path as url
from department import views
# SET THE NAMESPACE!
app_name = 'department'
# Be careful setting the name to just /login use userlogin instead!
urlpatterns=[

    url('register/',views.register,name='register'),
    url('user_login/',views.user_login,name='user_login'),
    url('course_add/', views.courseAdd, name='course_add'),
    url('notsadd/', views.Notification),
    url(r'^approve/(?P<student_id>\d+)$', views.approve_student, name='approve'),
    url('approve_all', views.approve_all, name='approve_all'),
    url(r'^reject/(?P<student_id>\d+)$', views.reject_student, name='reject'),
    url(r'^delete/(?P<course_id>\d+)$', views.courseDel, name='delete'),
    url(r'^not_delete/(?P<not_id>\d+)$', views.notDel, name='not_delete'),
    url(r'^unenroll/(?P<enroll_id>\d+)$', views.unEnroll, name='unenroll'),
    url(r'^download/(?P<course_id>\d+)$', views.downloadSyl, name='download'),
    url('assign_fac', views.assign_fac, name='assign_fac'),
    url('print_preview', views.enrollInfo, name='print_preview'),
    url('student_preview', views.StudentRegInfo, name='student_preview'),

    


]

department/models.py
from email.policy import default
from enum import unique
from pyexpat import model
from django.db import models
from django.contrib.auth.models import User

class DepProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    department_name = models.CharField(max_length=200)
    bio = models.TextField(max_length=500, blank=True, null=True)
    phone = models.CharField(max_length=12)
    website = models.URLField(blank=True)
    def __str__(self):
      return self.department_name

class CourseInfo(models.Model):
    slots =[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')]
    course_code = models.CharField(max_length=15, unique=True) 
    course_name = models.CharField(max_length=200)
    department = models.ForeignKey(DepProfileInfo, on_delete=models.CASCADE)
    start_date = models.DateField()
    slot = models.CharField(max_length=5, choices=slots, default='E')
    hours_per_week = models.IntegerField()
    no_of_seats = models.IntegerField()
    seats_left = models.IntegerField(blank=True, null=True)
    syllabus = models.FileField(upload_to='uploads/')
    def __str__(self) :
       return self.course_name

class ProgramInfo(models.Model):
    program_name = models.CharField(max_length=200)
    department = models.ForeignKey(DepProfileInfo, on_delete=models.CASCADE)

    def __str__(self) :
       return self.program_name

class Notification(models.Model):
  notification = models.TextField(max_length=400)
  department = models.ForeignKey(DepProfileInfo, on_delete=models.CASCADE)
  publish_date = models.DateField('date published', auto_now_add=True)

  def __str__(self) :
    return str(self.publish_date)

class Faculty(models.Model):
  user = models.OneToOneField(User,on_delete=models.CASCADE)
  name = models.CharField(max_length=200)
  department = models.ForeignKey(DepProfileInfo, on_delete=models.CASCADE)
  isCC = models.BooleanField(default=False)

  def __str__(self) -> str:
     return self.name

class Teaches(models.Model):
  faculty = models.OneToOneField(Faculty, on_delete=models.CASCADE)
  course = models.OneToOneField(CourseInfo, on_delete=models.CASCADE)
  
  def __str__(self) -> str:
     return str(self.faculty)

department/forms.py
from django import forms
from department.models import DepProfileInfo, CourseInfo, Faculty, Notification, Teaches
from django.contrib.auth.models import User
from bootstrap_datepicker_plus.widgets import DatePickerInput

class DepForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class DepProfileInfoForm(forms.ModelForm):
     class Meta():
         model = DepProfileInfo
         fields = ('department_name', 'bio','phone', 'website')



class CourseAddForm(forms.ModelForm):
    class Meta():    
        model = CourseInfo
        fields = ['course_code', 'course_name', 'start_date', 'slot','hours_per_week', 'no_of_seats', 'syllabus']
        # widgets = {
        #     'start_date': DatePickerInput(),
        # }

class NotForm(forms.ModelForm):
    class Meta():
        model= Notification
        fields =('notification',)

class FacForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    class Meta():
        model = User
        fields = ('username','password','email')
class FacultyForm(forms.ModelForm):
    class Meta():
        model = Faculty
        fields=('name', 'department', 'isCC')

class TeachesForm(forms.ModelForm):
    class Meta():
        model = Teaches
        fields=('faculty','course')
                

department/views.py
from ast import Delete
from django.shortcuts import render
from django.contrib import messages
from department.forms import DepForm,DepProfileInfoForm, CourseAddForm, NotForm, FacForm, FacultyForm, TeachesForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from department.models import CourseInfo, DepProfileInfo, Notification, Faculty, Teaches, ProgramInfo
from student.models import Enroll, StudentInfo
import os
import mimetypes


#@login_required(login_url='/')
def index(request):
    registered = False
    if request.method == 'POST':
        depinf = DepProfileInfo.objects.get(user=request.user)
        course_form = CourseAddForm(request.POST, request.FILES)
        if course_form.is_valid():
            course = course_form.save(commit=False)
            course.department=depinf
            course.save()
            seatadjsut()
            registered = True
            
        else:
            print(course_form.errors)
    else:
        course_form = CourseAddForm()
    
    registered = False
    if request.method == 'POST':
        f_user_form = FacForm(data=request.POST)
        f_profile_form = FacultyForm(data=request.POST)
        if f_user_form.is_valid() and f_profile_form.is_valid():
            user = f_user_form.save()
            user.set_password(user.password)
            user.save()
            f_profile = f_profile_form.save(commit=False)
            f_profile.user = user
            if 'profile_pic' in request.FILES:
                print('found it')
                f_profile.profile_pic = request.FILES['profile_pic']
            f_profile.save()
            registered = True
        else:
            print(f_user_form.errors,f_profile_form.errors)
    else:
        f_user_form = FacForm()
        f_profile_form = FacultyForm()
    
    if request.method == 'POST':
        depinf = DepProfileInfo.objects.get(user=request.user)
        nots_form = NotForm(data=request.POST)
        if nots_form.is_valid():
            
            nots = nots_form.save(commit=False)
            nots.department = depinf
            nots.save()
            nots_form = NotForm()
            registered = True
        else:
            print(nots_form.errors)
    else:
        nots_form = NotForm()

    if request.method == 'POST':
        
        tc_form = TeachesForm(data=request.POST)
        if tc_form.is_valid():
            
            tc = tc_form.save(commit=False)
            
            tc.save()
            registered = True
        else:
            print(tc_form.errors)
    else:
        tc_form = TeachesForm()
    
    if request.user.is_authenticated:
        depinf = DepProfileInfo.objects.get(user=request.user)
        cour = CourseInfo.objects.filter(department=depinf)
        notsin = Notification.objects.filter(department=depinf)
        student = StudentInfo.objects.filter(department=depinf)
        staff = Faculty.objects.filter(department=depinf)
        teaches = Teaches.objects.all()
        teach=[]
        for tch in teaches:
            if tch.course.department==depinf:
                teach.append(tch)
        enrolled = Enroll.objects.all()
        en_lst=[]
        for enr in enrolled:
            if enr.course.department==depinf:
                en_lst.append(enr)


        f_no_list =[st for st in staff if st not in [t.faculty for t in teaches]]
        c_no_list =[cs for cs in cour if cs not in [c.course for c in teaches]]
        course_form = CourseAddForm()
        f_user_form = FacForm()
        f_profile_form = FacultyForm()
        tc_form = TeachesForm()
        nots_form = NotForm()
        return render(request,'department/index.html', {'enrolled': en_lst,'teaches': teach, 'c_no_list': c_no_list,'f_no_list': f_no_list, 'tc_form':tc_form,'depinf':depinf,'notsin':notsin, 'cour': cour, 'course_form':course_form, 'nots_form': nots_form, 'student':student, 'f_user_form': f_user_form, 'f_profile_form': f_profile_form, 'staff': staff})




def welcome(request):
    deps=DepProfileInfo.objects.all()
    nots4 = Notification.objects.all().order_by('-id')[:4]
    nots = Notification.objects.all().order_by('-id')[4:]
    progs = ProgramInfo.objects.all()
    r=[]
    for d in deps:
        c = CourseInfo.objects.filter(department=d.id)
        r.append({'dep':d, 'cor':c})

    return render(request,'department/welcome.html', context={'progs':progs,'r':r, 'nots': nots, 'nots4':nots4, 'deps':deps  })


@login_required
def special(request):
    return HttpResponse("You are logged in !")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('welcome'))

def approve_student(request, student_id):
    student = User.objects.get(id=student_id)
    info = StudentInfo.objects.get(user=student)
    info.approved=True
    info.save()
    return HttpResponseRedirect(reverse('index'))

def approve_all(request):
    dep = DepProfileInfo.objects.get(user=request.user)
    st = StudentInfo.objects.filter(department=dep)
    for s in st:
        s.approved=True
        s.save()
    return HttpResponseRedirect(reverse('index'))

def reject_student(request, student_id):
    student = User.objects.get(id=student_id)
    info = StudentInfo.objects.get(user=student)
    info.delete()
    student.delete()
    return HttpResponseRedirect(reverse('index'))

def register(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        email = request.POST.get('email')
        if not (User.objects.filter(username=username).exists() or User.objects.filter(email=email).exists()):
            dep0 = User(username=username, email=email, is_staff=1)
            dep0.set_password(password)
            dep0.save()

            phone = request.POST.get('phone')
            department_name = request.POST.get('department_name')
            bio = request.POST.get('bio')
            website = request.POST.get('website')
            st_inf = DepProfileInfo(phone=phone, department_name=department_name, user_id=dep0.id, bio=bio, website=website)
            st_inf.save()
            messages.success(request, "Regitration Success!")
            return HttpResponseRedirect(reverse('welcome'))
        else: 
            messages.warning(request, "Username or email already exist!")
            return HttpResponseRedirect(reverse('welcome'))

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active and user.is_staff:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                messages.warning(request, "You are not a Department!")
                return HttpResponseRedirect(reverse('welcome'))
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(username,password))
            messages.warning(request, "Invalid login details given")
            return HttpResponseRedirect(reverse('welcome'))
    else:
        return HttpResponseRedirect(reverse('welcome'))

def courseAdd(request):
    registered = False
    if request.method == 'POST':
        course_form = CourseAddForm(request.POST, request.FILES)
        if course_form.is_valid():
            
            course = course_form.save(commit=False)
            course.start_date = request.POST.get('start-date')
            print(course)
            course.save()
            registered = True
            
        else:
            print(course_form.errors)
    else:
        course_form = CourseAddForm()
    seatadjsut()
    return render(request,'department/',
                          {
                           'course_form':course_form,
                           'registered':registered})

def seatadjsut():
    c = CourseInfo.objects.all().order_by('-id')[0]
    print(c)
    c.seats_left = c.no_of_seats
    c.save()

def courseDel(request, course_id):
    print(course_id)
    crs=CourseInfo.objects.get(id=course_id)
    crs.delete()
    
    return HttpResponseRedirect(reverse('index'))

def notDel(request, not_id):
    nt=Notification.objects.get(id=not_id)
    nt.delete()
    return HttpResponseRedirect(reverse('index'))

def unEnroll(request, enroll_id):
    enroled = Enroll.objects.get(id=enroll_id)
    enroled.delete()
    cor = CourseInfo.objects.get(id=enroled.course.id)
    cor.seats_left+=1
    cor.save()
    return HttpResponseRedirect(reverse('index'))

def downloadSyl(request, course_id):
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    corse= CourseInfo.objects.get(id=course_id)
    paths = corse.syllabus.url
    filepath = BASE_DIR + paths
    #path = open(filepath, 'r', encoding='utf-8')
    with open(filepath, 'rb') as f:
        path = f.read()
    mime_type, _ = mimetypes.guess_type(filepath)
    response = HttpResponse(path, content_type=mime_type)
    # Set the HTTP header for sending to browser
    response['Content-Disposition'] = "attachment; filename=%s.pdf" % "syllabus"
    # Return the response value
    return response

def enrollInfo(request):
    dep = DepProfileInfo.objects.get(user_id=request.user.id)
    enrol = Enroll.objects.all()
    enr_dep=[]
    for en_s in enrol:
        if en_s.student.department == dep:
            enr_dep.append(en_s)
    return render(request,'department/EnrollData.html', {'enroll':enr_dep, 'dep':dep })

def StudentRegInfo(request):
    dep = DepProfileInfo.objects.get(user_id=request.user.id)
    enrol = Enroll.objects.all()
    enr_dep=[]
    for en_s in enrol:

templates/department/DepStudents.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Student Details</title>
</head>
<body>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
    <table border='1px' class="table">
        <thead class="thead-dark">
        <tr scope="row">
            <th colspan="5" scope="col"><center>
                {{dep}}
            </center>
            </th>
        </tr>
    </thead>
    <thead class="thead-dark">
        <tr scope="row">

            <th scope="col">Reg No.</th>
            <th scope="col">Full Name</th>
            <th scope="col">Programme</th>
            <th scope="col">Department</th>
            <th scope="col">Enrolled Course</th>
        </tr>
    </thead>
        {% for s in student%}
        <tr scope="row">
            <td scope="col">
                {{s.student.exam_reg_no}}
            </td>
            <td scope="col">
                {{s.student.user.first_name}} {{s.student.user.last_name}}
            </td>
            <td scope="col">
                {{s.student.course}}
            </td>
            <td scope="col">
                {{s.student.department}}
            </td>
            <td scope="col">
                {{s.course}}
            </td>
        </tr>
        {% endfor %}

      </table>
    </div>
    </div>
    <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2 mr-0">
        <div class="container ">
            <a id="print" class="btn btn btn-dark text-white" onclick="t_id=document.getElementById('print');t_id.style.visibility='hidden'; window.print();return false;">Print</a>
    
        </div>
    </div>
    <div class="col-md-5"></div>
    </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</body>
</html>

templates/department/EnrollData.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Student Enroll Details</title>
</head>
<body>
    <br>
    <div class="container-fluid">
        <div class="row">
            <div class="col">
    <table border='1px' class="table">
        <thead class="thead-dark">
        <tr scope="row">
            <th colspan="5" scope="col"><center>
                {{dep}}
            </center>
            </th>
        </tr>
    </thead>
    <thead class="thead-dark">
        <tr scope="row">
            
            <th scope="col">Reg No.</th>
            <th scope="col">Full Name</th>
            <th scope="col">Programme</th>
            <th scope="col">Department</th>
            <th scope="col">Enrolled Course</th>
            
        </tr>
    </thead>
        {% for s in enroll%}
        <tr scope="row">
            <td scope="col">
                {{s.student.exam_reg_no}}
            </td>
            <td scope="col">
                {{s.student.user.first_name}} {{s.student.user.last_name}}
            </td>
            <td scope="col">
                {{s.student.course}}
            </td>
            <td scope="col">
                {{s.course.department}}
            </td>
            <td scope="col">
                {{s.course}}
            </td>
        </tr>
        {% endfor %}

        
    </table>
    </div>
    </div>
    <div class="row">
    <div class="col-md-5"></div>
    <div class="col-md-2 mr-0">
        <div class="container ">
            <a id="print" class="btn btn btn-dark text-white" onclick="t_id=document.getElementById('print');t_id.style.visibility='hidden'; window.print();return false;">Print</a>
    
        </div>
    </div>
    <div class="col-md-5"></div>
    </div>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
</body>
</html>

templates/department/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>IDCP</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.9.1/font/bootstrap-icons.css">
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css"> -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="../../static/styles.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
</head>

  <body style="background-color: rgb(29, 29, 29);">
    <hr>


    <div class="container bg-light rounded" style=" background-image: url('/static/bg.webp');" >


    <br>

      <a href="{% url 'welcome' %}" class="text-dark text-decoration-none"><div class="jumbotron" style="background-image: url('../../static/campus.png');background-repeat: no-repeat;background-size: cover;">



        <h3 class="text-white"><b> Interdisciplinary Course Portal</b></h3>
        <h6 class="text-white"><b>Cochin University of Science and Technology</b> </h6>
        <!-- {% if user.is_authenticated %}
            <h5>Hello {{ user.username }}</h5>


        {% endif %} -->
      </div></a>


    <div>
    {% block body_block %}

    {% endblock %}
    </div>
    </div>
    <hr>
    <div class="footer-clean text-white" style="background-color: #353535;">
      <footer>
          <div class="container">
              <div class="row justify-content-center">
                  <div class="col-sm-4 col-md-3 item">
                      <h3>Quick Links</h3>
                      <ul>
                          <li><a href="https://cusat.ac.in/"  target="_blank">University Website</a></li>
                          <li><a href="https://estudents.cusat.ac.in/"  target="_blank">E Students Portal</a></li>
                          <li><a href="https://dca.cusat.ac.in/"  target="_blank">DCA Website</a></li>
                      </ul>
                  </div>
                  <div class="col-sm-4 col-md-3 item">
                      <h3>Help</h3>
                      <ul>
                          <li><a href="#"  target="_blank">Department User Guide</a></li>
                          <li><a href="#"  target="_blank">Student User Guide</a></li>
                          <li><a href="mailto:idcpcusat@gmail.com" target="_blank">Support</a></li>
                      </ul>
                  </div>

                  <div class="col-sm-4 col-md-3 item">
                    <h3>About</h3>
                    <ul>
                        <li><a href="{% url 'project' %}"  target="_blank">Project</a></li>
                        <li><a href="{% url 'team' %}"  target="_blank">Team</a></li>
                        <li><a href="mailto:idcpcusat@gmail.com">Feedbacks</a></li>
                    </ul>
                </div>

                  <div class="col-lg-3 item social">
                    <!-- <a href="#"><i class="icon ion-social-facebook"></i></a><a href="#"><i class="icon ion-social-twitter"></i></a><a href="#"><i class="icon ion-social-snapchat"></i></a><a href="#"><i class="icon ion-social-instagram"></i></a> -->
                    <p><a href="{% url 'welcome' %}" class="text-white">IDCP @ 2022 </a> </p>
                  </div>
              </div>
          </div>
      </footer>
    </div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
     -->

     <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
     <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
     <script src="../../static/login.js"></script>
  </div>
  </body>
</html>

templates/department/login.html
{% block login %}
  <div class="container">
    <br>
    <div class="card col-md-4 text-center" style="margin: 0 auto; float: none; margin-bottom: 10px;"><br>
      <h3>Login</h3>
      <br>
  <form method="post" action="{% url 'department:user_login' %}">
          {% csrf_token %}
          {# A more "HTML" way of creating the login form#}
          <label for="username">Username:</label>
          <input type="text" name="username" placeholder="Username"><br>
          <label for="password">Password:</label>
          <input type="password" name="password" placeholder="Password"><br><br>
          <input type="submit" name="" value="Login">&nbsp;
New user?&nbsp;&nbsp;<a href="{% url 'department:register' %}">Register</a><br><br>
</form>
  </div>
</div>
{% endblock %}

templates/department/registration.html
{% extends "department/base.html" %}
{% load static %}
{% block body_block %}

<!-- <nav class="navbar navbar-expand-lg navbar-light bg-white">
  <a class="navbar-brand" href="{% url 'welcome' %}">IDCP</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon navbar-light"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li><a class="navbar-link  text-dark" href="#">Student Login</a></li>&nbsp;&nbsp; 
        {# Some logic on what to display for last item#}
        <!-- {% if user.is_authenticated %}
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a class="navbar-link  text-dark" href="{% url 'department:user_login' %}">Department Login</a></li>
        {% endif %} 
    </ul>
  </div>
</nav> -->
<div class="container">
<!-- <div class="jumbotron" style="background-image: url('../../static/campus.png');background-repeat: no-repeat;background-size: cover;">
  <h2><B>Interdisciplinary Course Portal</B></h2>
  <h4>Cochin University of Science and Technology</h4>
  {% if user.is_authenticated %}
      <h5>Hello {{ user.username }}</h5>
  

  {% endif %}
</div> -->

  <div class="container">
    <div class="card" style="margin: 0 auto; float: none; margin-bottom: 10px;">
      {% if registered %}
        <h1>Thank you for registering!</h1>
      {% else %}
        <h1>Register Here</h1>
        <h3>Just fill out the form.</h3>
<form enctype="multipart/form-data" method="POST">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}
          <input type="submit" name="" value="Register">
        </form>
        
      {% endif %}
    </div>
  </div>
{% endblock %}